#!/bin/bash

# Import from paranoid
# Edit By Xilence2210

# get current path
reldir=`dirname $0`
cd $reldir
DIR=`pwd`

# Colorize and add text parameters
red=$(tput setaf 1)             #  red
grn=$(tput setaf 2)             #  green
cya=$(tput setaf 6)             #  cyan
txtbld=$(tput bold)             # Bold
bldred=${txtbld}$(tput setaf 1) #  red
bldgrn=${txtbld}$(tput setaf 2) #  green
bldblu=${txtbld}$(tput setaf 4) #  blue
bldcya=${txtbld}$(tput setaf 6) #  cyan
txtrst=$(tput sgr0)             # Reset

THREADS="16"
DEVICE="$1"
SYNC="$2"
EXTRAS="$3"

if [ "carbon$DEVICE" == "carbon" ]
then
#   clear
   echo " "
   echo "==================================================="
   echo " "
   echo " Skrypt budowy Carbon ROM"
   echo " -------------------"
   echo " "
   echo " "
   echo " Uzycie: './cb [Device] {Variable}'"
   echo "   Device - your device name"
   echo "   Variable - functions"
   echo "      fix   :start build without any cleanning for fix build"
   echo "      clean :run 'make installclean' before build"
   echo "      sync  :run 'repo sync' before build"
   echo " "
   echo " e.g './cb codina sync clean'"
   echo " "
   exit 0
fi

# we don't allow scrollback buffer
echo -e '\0033\0143'
# clear

echo -e "${cya}Building ${bldcya} Carbon ROM project ${txtrst}";

# setup environment
echo -e "${bldblu}Setting up environment ${txtrst}"
export USE_CCACHE=1
export CCACHE_DIR=~/.carboncache
# set ccache due to your disk space,set it at your own risk
prebuilts/misc/linux-x86/ccache/ccache -M 6G
. build/envsetup.sh

add_lunch_combo carbon_codina-userdebug
export PATH=${PATH}:~/bin
export PATH=${PATH}:~/android-sdk/tools
export PATH=${PATH}:~/android-sdk/platform-tools

# lunch device
# echo -e ""
# echo -e "${bldblu}Lunching device ${txtrst}"
# lunch carbon_$DEVICE-userdebug

fix_count=0
# excute with vars
echo -e ""
for var in $* ; do
if [ "$var" == "sync" ]
then
   echo -e "${bldblu}Fetching latest sources ${txtrst}"
   if [ -d "$ADDON" ]
   then
      echo -e "fetching add-on repo"
      echo -e "change this at script line 28"
      cd $ADDON
      git pull
      cd $DIR
      echo -e "=============================================="
   fi
   repo sync
   echo -e ""
elif [ "$var" == "clean" ]
then
   echo -e "${bldblu}Clearing previous build info ${txtrst}"
   mka installclean
elif [ "$var" == "fix" ]
then
   echo -e "skip for remove build.prop"
   fix_count=1
fi
done
if [ "$fix_count" == "0" ]
then
   echo -e "removing build.prop"
   rm -f $OUT_DIR/system/build.prop
fi

echo -e ""
echo -e "${bldblu}Starting compilation ${txtrst}"

# get time of startup
res1=$(date +%s.%N)

# start compilation
# echo -e "${bldblu}breakfasting device ${txtrst}"
# breakfast $DEVICE
echo -e "${bldblu}brunching device ${txtrst}"
brunch $DEVICE -j4
# time mka -j4 carbon
# make -j8 bacon
echo -e ""

# finished? get elapsed time
res2=$(date +%s.%N)
echo "${bldgrn}Total time elapsed: ${txtrst}${grn}$(echo "($res2 - $res1) / 60"|bc ) minutes ($(echo "$res2 - $res1"|bc ) seconds) ${txtrst}"

# make a alarm
echo $'\a'
